#import "../template.typ": template
#show: template

= The action principle

- For small $delta s in RR$, $f(s + delta s) = f(s) + (d f(s)) / (d s) delta s + R(s, delta s)$
- With $delta f := f(s + delta s) - f(s)$, $delta f = (d f(s)) / (d s) delta s + R(s, delta s)$, with $ lim_(delta s -> 0) R(s, delta s) / (delta s) = 0 $ So $delta f$ vanishes to first order in $delta s$, so $R(s, delta s)$ can be written as $O((delta s)^2)$
- At the extrema of $f$, $(d f(s)) / (d s) = 0$ so $delta f = O((delta s)^2)$
- *Functional*: map from functions to $RR$
- $y(t)$ *stationary* for functional $S$ if $ (d S[y(t) + epsilon z(t)]) / (d e) divides_(epsilon = 0) = 0 $ for every smooth $z(t)$ with $z(a) = z(b) = 0$. We use the notation $delta y(t) = epsilon z(t)$. $y(t)$ is called a *path*.
- *Action principle (variational principle)*: paths described by particles are stationary paths of $S$: $ delta S := S[x + delta x] - S[x] = O((delta x)^2) $ for arbitrary smooth small deformations $delta x(t)$ around true path $x(t)$.
- *Fundamental lemma of the calculus of variations*: Let $f(x)$ be continuous in $[a, b]$ and $ integral_a^b f(x) g(x) dif x = 0 $ for every smooth $g(x)$ in $[a, b]$ with $g(a) = g(b) = 0$. Then $f(x) = 0$ in $[a, b]$.
- *Notation*: $ (diff L) / (diff x) = (diff L(r, s)) / (diff r) divides_((r, s) = (x(t), dot(x)(t))), quad (diff L) / (diff dot(x)) = (diff L(r, s)) / (diff s) divides_((r, s) = (x(t), dot(x)(t))) $
- For a path $underline(q)$ and a Lagrangian $L(underline(q), underline(dot(q)))$, the action for the path is $ S = integral_(t_0)^(t_1) L(underline(q)(t), underline(dot(q))(t))) dif t $
- The action above satisfies $ 0 = delta S = integral_(t_0)^(t_1) (sum_(i = 1)^N (diff L) / (diff q_i) delta q_i + sum_(i = 1)^N (diff L) / (diff dot(q)_i) delta dot(q)_i) dif t $
- *Euler-Lagrange equation*: $ (diff L) / (diff x) - d / (d t) ((diff L) / (diff dot(x))) = 0 $
- The arguments in a Lagrangian, $x$ and $dot(x)$, are independent: $ (diff x) / (diff dot(x)) = (diff dot(x)) / (diff x) = 0 $
- *Configuration space, $cal(C)$*: set of all possible instantaneous confiugratinons of a physical system. (Includes positions but not velocities).
- For configuration space $cal(C)$ of system $cal(S)$, $S$ has $dim(cal(C))$ *degrees of freedom*.
- *Generalised coordinates*: A set of coordinates in configuration space.
- Notation: $underline(q)$ shows results holds for arbitrary choices of generalised coordinates.
- *Euler-Lagrange equation for configuration space $cal(C)$*: $ (diff L) / (diff q_i) - d / (d t) ((diff L) / (diff dot(q)_i)) = 0 quad forall i in {1, ..., dim(cal(C))} $
- For system with kinetic energy $T(underline(q), underline(dot(q)))$ and potential energy $V(underline(q))$, the Lagrangian for the system is $ L(underline(q), underline(dot(q))) = T(underline(q), underline(dot(q))) - V(underline(q)) $
- *Ignorable coordinate $q_i$*: Lagrangian does not depend on $q_i$: $ (diff L(q_1, ... q_N, dot(q)_1, ... dot(q)_N)) / (diff q_i) = 0 $
- *Generalised momentum* of coordinate $q_i$: $ p_i := (diff L) / (diff dot(q)_i) $
- Generalised momentum of ignorable coordinate is conserved.

= Symmetries, Noether's theorem and conservation laws

- *Transformation depending on $epsilon$*: family of smooth maps $phi(epsilon): cal(C) -> cal(C)$ with $phi(0)$ the identity map. Can be written as $ q_i -> q_i' = phi.alt_i(q_1, ..., q_N, epsilon) $ where the $phi.alt_i$ are a set of $N = dim(cal(C))$ functions representing the transformation in the given coordinate system. Change in velocities is $ dot(q)_i -> d/(d t) phi.alt_i $
- *Generator of $phi$*: $ (d phi(epsilon)) / (d epsilon) divides_(epsilon = 0) = phi'(0) $
- In any coordinate system, $ q_i -> phi.alt_i(underline(q), epsilon) = q_i + epsilon a_i(underline(q)) + O(epsilon^2) $ where $ a_i = (diff phi.alt_i(underline(q), epsilon)) / (diff epsilon) divides_(epsilon = 0) $ So the generator of the transformation is $a_i$.
- For velocities, $ dot(q)_i -> dot(q)_i + epsilon dot(a)_i (q_1, ..., q_N, dot(q)_1, ..., dot(q)_N) + O(epsilon^2) $ generated by $dot(a)_i$.
- Equations of motion don't change when total derivative of function of coordinates and time is added to Lagrangian: $ L -> L + (d F(q_1, ..., q_N, t)) / (d t) $ doesn't change equations of motion.
- Transformation $phi(epsilon)$ is *symmetry* if for some $F(underline(q), t)$, $ L -> L' = L(phi.alt(q_1, epsilon), ..., phi.alt(q_N, epsilon)) = L + epsilon (d F(q_1, ..., q_N, t)) / (d t) + O(epsilon^2) $ $F(underline(q), t)$ defined up to a constant.
- For ignorable coordinate $q_i$, transformation $q_i -> q_i + c_i$ is symmetry since $q_i$ doesn't appear in Lagrangian and $dot(q)_i$ stays invariant. So $F = 0$ here and $a_k = delta_(i k)$.
- *Noether's theorem*: Let a symmetric transformation be generated by $a_i(q_1, ..., q_N)$, so $ L -> L + epsilon (d F(q_1, ..., q_N, t)) / (d t) + O(epsilon^2) $ Then $ Q := (sum_(i = 1)^N a_i (diff L) / (diff dot(q)_i)) - F $ is conserved (so $(d Q) / (d t) = 0$).
- $Q$ is called *Noether charge*.
- Given Lagrangian $L(underline(q), underline(dot(q)), t)$, *energy* is $ E := (sum_(i = 1)^N dot(q)_i (diff L) / (diff dot(q)_i)) - L $
- Along path $underline(q)(t)$ satisfying equations of motion, $ (d E)/(d t) = -(diff L)/(diff t) $
- So energy conserved iff Lagrangian doesn't depend explicitly on time.

= Normal modes

- *Canonical* kinetic term: of the form $T = 1/2 sum_(i = 1)^n dot(q)_i^2$.
- *Normal mode*: solution to $dot.double(underline(q)) + A underline(q) = 0$, associated with eigenvalue $lambda^((i)) > 0$ of $A$, of form $ underline(q)(t) = underline(v)^((i)) (alpha^((i)) cos(sqrt(lambda^((i))) t) + beta^((i)) sin(sqrt(lambda^((i))) t)) $
- *Zero mode*: solution to $dot.double(underline(q)) + A underline(q) = 0$, associated with eigenvalue $lambda^((i)) = 0$ of $A$, of form $ underline(q)(t) = underline(v)^((i)) (alpha^((i)) t + beta^((i))) $
- *Instability*: solution to $dot.double(underline(q)) + A underline(q) = 0$, associated with eigenvalue $lambda^((i)) < 0$ of $A$, of form $ underline(q)(t) = underline(v)^((i)) (alpha^((i)) cosh(sqrt(-lambda^((i))) t) + beta^((i)) sinh(sqrt(-lambda^((i))) t)) $
- When no instabilities, general solution is superposition (sum) of normal modes and zero modes.

= Fields and the wave equation

- *Generalised Euler-Lagrange equations for fields*: $ (diff cal(L)) / (diff u) - diff / (diff x) ((diff cal(L)) / (diff u_x)) - diff / (diff t) ((diff cal(L)) / (diff u_t)) = 0 $ and for $n$ fields $u^((i))$: $ (diff cal(L)) / (diff u^((i))) - diff / (diff x) ((diff cal(L)) / (diff u_x^((i)))) - diff / (diff t) ((diff cal(L)) / (diff u_t^((i)))) = 0 quad forall i $
- If fields don't depend on $(t, x)$ but on $d$ coordinates $x_i$, $ (diff cal(L)) / (diff u^((i))) - sum_(k = 1)^d diff / (diff x_k) ((diff cal(L)) / (diff u_k^((i)))) $ where $u_k^((i)) = (diff u^((i))) / (diff x_k)$
- *Massless scalar field Lagrangian*: $ cal(L) = 1/2 rho u_t^2 - 1/2 tau u_x^2 $ $rho$ is *density*, $tau$ is *tension*. The field $u$ is the *massless scalar*.
- Equation of motion for massless scalar field is $ rho u_(t t) - tau u_(x x) = 0 $ which rearranges to *wave equation*: $ u_(t t) = c^2 u_(x x) $ where $c^2 = tau \/ rho$.
- *D'Alembert's solution to wave equation*: $ u(x, t) = f(x - c t) + g(x + c t) $ $f(x - c t)$ corresponds to a wave moving to the right with speed $c$, $g(x + c t)$ corresponds to a wave moving to the left with speed $c$.
- If $u(x, 0) = phi(x)$ and $u_t(x, 0) = psi(x)$ then $ u(x, t) = 1/2 (phi(x - c t) + phi(x + c t)) + 1/(2c) integral_(x - c t)^(x + c t) psi(s) dif s $
- In field theory, *symmetry* is transformation $ u -> u' = u + epsilon a(u) $ such that $delta cal(L) = O(epsilon^2)$. $a(u)$ *generates* the transformation.
- *Note*: often, $x_0$ chosen to be $t$.
- Let $u_i = (diff u) / (diff x_i)$, *generalised momentum vector* is $ underline(Pi) := ((diff cal(L)) / (diff u_0), ..., (diff cal(L)) / (diff u_d)) $
- *Noether current* associated to transformation generated by $a$ is $ underline(J) = a underline(Pi) $
- If $underline(J)$ associated to symmetry, $ underline(nabla) dot.op underline(J) = sum_(i = 0)^d (diff J_i) / (diff x_i) = 0 $
- *(Noether) charge density*: $ cal(Q) := J_0 $
- For $d = 1$, *charge contained in interval $(a, b)$*: $ Q_((a, b)) = integral_a^b cal(Q) dif x $
- For $d = 1$, $ (d Q_((a, b))) / (d t) = J_1(a) - J_1(b) $
- *Noehter charge* is total charge over all space. For $d = 1$: $ Q := Q_((-oo, oo)) = integral_(-oo)^oo J_0 dif x $
- If $d = 1$ and $lim_(x -> plus.minus oo) J_1 = 0$, $ (d Q) / (d t) = 0 $
- *Energy-momentum tensor*: $ T_(i j) := (diff cal(L)) / (diff u_j) (diff u) / (diff x_i) - delta_(i j) cal(L) $
- *Energy density*: $ cal(E) := T_(0 0) $
- *Conservation law for energy-momentum tensor*: $ sum_(j = 0)^d (diff T_(i j)) / (diff x_j) = 0 $
- *Dirichlet boundary condition* for wave equation: $u_t(0, t) = 0$ (so $u(0, t) = 0$ as $u$ has shift symmetry) which gives $ u(x, t) = f(x - c t) - f(-x - c t) $ Here, waves reflected off boundary and turned upside down.
- *Neumann (free) boundary condition*: $u_x(0, t) = 0$ which gives $ u(x, t) = f(x - c t) + f(-x - c t) $ So waves reflected off boundary and not turned upside down.
- *Junction conditions*:
	- $u$ continuous at $0$: $ lim_(epsilon -> 0^+) u(epsilon, t) = lim_(epsilon -> 0^-) u(epsilon, t) $
	- Energy conservation across junction: $ d/(d t) (lim_(epsilon -> 0) T(-epsilon, epsilon)) = lim_(epsilon -> 0) (T_(t x))_(x = -epsilon) - lim_(epsilon -> 0) (T_(t x))_(x = epsilon) $
- *Ansatz for wave function with spring at junction at $x = 0$*: $ u(x, t) = cases(
	"Re"((e^(i p x) + R e^(-i p x)) e^(-i p c t)) & "if" x <= 0,
	"Re"(T e^(i p(x - c t))) & "if" x > 0
) $