- *Lemma 4.19*:
    - Well-defined: show that $lambda_1 tilde.eq lambda_2 ==> f compose lambda_1 tilde.eq f compose lambda_2$ (use definition of $lambda_1 tilde.eq lambda_2$).
    - Homomorphism: use that $f compose (lambda * mu) = (f compose lambda) * (f compose mu)$.
- *Lemma 4.20*: for loop $lambda$ in $(X, x_0)$, find based homotopy between $f compose lambda$ and $g compose lambda$ in terms of based homotopy $H$ between $f$ and $g$.
- *Lemma 4.21*: straightforward, just use the definition of $f_*$.
- *Corollary 4.22*: use definition of homotopy equivalent based spaces and lemma 4.21, to show the induced homomorphisms of the homotopy equivalences are inverse to each other.
- *Theorem 4.23*:
    - There is path $p$ from $x_0$ to $x_1$.
    - Let $lambda$ loop in $X$ based at $x_0$.
    - Define $overline(p)(s) = p(1 - s)$, define loop $lambda_p$ in $X$ based at $x_1$ by $ lambda_p (s) = cases(overline(p(3s)) & "if" s in [0, 1\/3], lambda(3s - 1) & "if" s in [1\/3, 2\/3], p(3s - 2) & "if" s in [2\/3, 1]) $
    - Claim: $ Phi_p: pi_1 (X, x_0) -> pi_1 (X, x_1), quad Phi([lambda]) = [lambda_p] $ is isomorphism.
        - Well-defined: show if $lambda, mu$ loops based at $x_0$, $lambda tilde.eq mu ==> lambda_p tilde.eq mu_p$ by homotopy diagram (merge $overline(p), lambda, p$ on bottom and $overline(p), mu, p$ on top).