- *Lemma 7.8*:
    - Consider $I$ for which statement does not hold, with $N(I)$ minimal, then there are $b, b' in.not I$ but $b b' in I$.
- *Theorem 7.9*:
    - Define $A = {x in K: x P subset.eq cal(O)_K}$, show $A$ is fractional ideal and $R subset.eq A$
    - Show $A != cal(O)_K$:
        - Choose $0 != alpha in P$, choose prime ideals such that $P_1 dots.h.c P_t subset.eq (alpha)$ and $t$ is minimal.
        - Choose $beta in P_2 dots.h.c P_t$ and $beta in.not (alpha)$, show that $beta/alpha in A - R$.
    - Show that $P != A P$, using Theorem 4.6.
    - Use fact that $P$ is maximal to conclude $A P = R$.
- *Lemma 8.4*:
    - Clear when $I$ or $J$ is $cal(O)_K$ so assume both are proper.
    - Sufficient to show for when $J$ is prime (why?)
    - Use that $N(I P) = |R\/ (I P)| = |R\/I| dot.op |I\/(I P)|$.
    - Show that $|I\/(I P)| = |R\/P|$:
        - Show $I\/(I P)$ is one-dimensional vector space over $R\/P$:
            - Show $I != I P$ and choose $x in I - (I P)$.
            - Show $(x, I P) = I$ using unique factorisation.