import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image";
import pageTitle from "../lib/title";
import styles from "../styles/Home.module.scss";

export default function Home() {
	return (
		<div>
			<Head>
				<title>{pageTitle("Home")}</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<div className={styles.container}>
				<h1>{"Hi, I'm Isaac"}</h1>
			</div>
		</div>
	)
}