- *Proposition 4.4*: show $dim((C^perp)^perp) = dim(C)$ and $C subset.eq (C^perp)^perp$.
- *Proposition 4.5*: show $forall y in FF_q^(n - k)$, $y H in C^perp$, let $f_H (y) = y H$ so $"im"(f_H) subset.eq C^perp$ and show $dim("im"(f_H)) = dim(C^perp)$.
- *Proposition 4.6*: similar to prop 4.5, use that $P^T = P^(-1)$.