#import "../../template.typ": template
#show: template

= The action principle

- For small $delta s in RR$, $f(s + delta s) = f(s) + (d f(s)) / (d s) delta s + R(s, delta s)$
- With $delta f := f(s + delta s) - f(s)$, $delta f = (d f(s)) / (d s) delta s + R(s, delta s)$, with $ lim_(delta s -> 0) R(s, delta s) / (delta s) = 0 $ So $delta f$ vanishes to first order in $delta s$, so $R(s, delta s)$ can be written as $O((delta s)^2)$
- At the extrema of $f$, $(d f(s)) / (d s) = 0$ so $delta f = O((delta s)^2)$
- *Functional*: map from functions to $RR$
- $y(t)$ *stationary* for functional $S$ if $ (d S[y(t) + epsilon z(t)]) / (d epsilon) divides_(epsilon = 0) = 0 $ for every smooth $z(t)$ with $z(a) = z(b) = 0$. We use the notation $delta y(t) = epsilon z(t)$. $y(t)$ is called a *path*.
- *Action principle (variational principle)*: paths described by particles are stationary paths of $S$ (an action functional): $ delta S := S[x + delta x] - S[x] = O((delta x)^2) $ for arbitrary smooth small deformations $delta x(t)$ around true path $x(t)$.
- *Fundamental lemma of the calculus of variations*: Let $f(x)$ be continuous in $[a, b]$ and $ integral_a^b f(x) g(x) dif x = 0 $ for every smooth $g(x)$ in $[a, b]$ with $g(a) = g(b) = 0$. Then $f(x) = 0$ in $[a, b]$.
- *Notation*: $ (diff L) / (diff x) = (diff L(r, s)) / (diff r) divides_((r, s) = (x(t), dot(x)(t))), quad (diff L) / (diff dot(x)) = (diff L(r, s)) / (diff s) divides_((r, s) = (x(t), dot(x)(t))) $
- For a path $underline(q)$ and a Lagrangian $L(underline(q), underline(dot(q)))$, the action for the path is $ S = integral_(t_0)^(t_1) L(underline(q)(t), underline(dot(q))(t))) dif t $
- The action above satisfies $ 0 = delta S = integral_(t_0)^(t_1) (sum_(i = 1)^N (diff L) / (diff q_i) delta q_i + sum_(i = 1)^N (diff L) / (diff dot(q)_i) delta dot(q)_i) dif t $
- *Euler-Lagrange equation*: $ (diff L) / (diff x) - d / (d t) ((diff L) / (diff dot(x))) = 0 $
- The arguments in a Lagrangian, $x$ and $dot(x)$, are independent: $ (diff x) / (diff dot(x)) = (diff dot(x)) / (diff x) = 0 $
- *Configuration space, $cal(C)$*: set of all possible instantaneous confiugratinons of a physical system. (Includes positions but not velocities).
- For configuration space $cal(C)$ of system $cal(S)$, $S$ has $dim(cal(C))$ *degrees of freedom*.
- *Generalised coordinates*: A set of coordinates in configuration space.
- Notation: $underline(q)$ shows results holds for arbitrary choices of generalised coordinates.
- *Euler-Lagrange equation for configuration space $cal(C)$*: $ (diff L) / (diff q_i) - d / (d t) ((diff L) / (diff dot(q)_i)) = 0 quad forall i in {1, ..., dim(cal(C))} $
- For system with kinetic energy $T(underline(q), underline(dot(q)))$ and potential energy $V(underline(q))$, the Lagrangian for the system is $ L(underline(q), underline(dot(q))) = T(underline(q), underline(dot(q))) - V(underline(q)) $
- *Ignorable coordinate $q_i$*: Lagrangian does not depend on $q_i$: $ (diff L(q_1, ... q_N, dot(q)_1, ... dot(q)_N)) / (diff q_i) = 0 $
- *Generalised momentum* of coordinate $q_i$: $ p_i := (diff L) / (diff dot(q)_i) $
- Generalised momentum of ignorable coordinate is conserved.

= Symmetries, Noether's theorem and conservation laws

- *Transformation depending on $epsilon$*: family of smooth maps $phi(epsilon): cal(C) -> cal(C)$ with $phi(0)$ the identity map. Can be written as $ q_i -> q_i' = phi.alt_i(q_1, ..., q_N, epsilon) $ where the $phi.alt_i$ are a set of $N = dim(cal(C))$ functions representing the transformation in the given coordinate system. Change in velocities is $ dot(q)_i -> d/(d t) phi.alt_i $
- *Generator of $phi$*: $ (d phi(epsilon)) / (d epsilon) divides_(epsilon = 0) = phi'(0) $
- In any coordinate system, $ q_i -> phi.alt_i(underline(q), epsilon) = q_i + epsilon a_i(underline(q)) + O(epsilon^2) $ where $ a_i = (diff phi.alt_i(underline(q), epsilon)) / (diff epsilon) divides_(epsilon = 0) $ So the generator of the transformation is $a_i$.
- For velocities, $ dot(q)_i -> dot(q)_i + epsilon dot(a)_i (q_1, ..., q_N, dot(q)_1, ..., dot(q)_N) + O(epsilon^2) $ generated by $dot(a)_i$.
- Equations of motion don't change when total derivative of function of coordinates and time is added to Lagrangian: $ L -> L + (d F(q_1, ..., q_N, t)) / (d t) $ doesn't change equations of motion.
- Transformation $phi(epsilon)$ is *symmetry* if for some $F(underline(q), t)$, $ L -> L' = L(phi.alt(q_1, epsilon), ..., phi.alt(q_N, epsilon)) = L + epsilon (d F(q_1, ..., q_N, t)) / (d t) + O(epsilon^2) $ $F(underline(q), t)$ defined up to a constant.
- For ignorable coordinate $q_i$, transformation $q_i -> q_i + c_i$ is symmetry since $q_i$ doesn't appear in Lagrangian and $dot(q)_i$ stays invariant. So $F = 0$ here and $a_k = delta_(i k)$.
- *Noether's theorem*: Let a symmetric transformation be generated by $a_i(q_1, ..., q_N)$, so $ L -> L + epsilon (d F(q_1, ..., q_N, t)) / (d t) + O(epsilon^2) $ Then $ Q := (sum_(i = 1)^N a_i (diff L) / (diff dot(q)_i)) - F $ is conserved (so $(d Q) / (d t) = 0$).
- $Q$ is called *Noether charge*.
- Given Lagrangian $L(underline(q), underline(dot(q)), t)$, *energy* is $ E := (sum_(i = 1)^N dot(q)_i (diff L) / (diff dot(q)_i)) - L $
- Along path $underline(q)(t)$ satisfying equations of motion, $ (d E)/(d t) = -(diff L)/(diff t) $
- So energy conserved iff Lagrangian doesn't depend explicitly on time.

= Normal modes

- *Canonical* kinetic term: of the form $T = 1/2 sum_(i = 1)^n dot(q)_i^2$.
- *Normal mode*: solution to $dot.double(underline(q)) + A underline(q) = 0$, associated with eigenvalue $lambda^((i)) > 0$ of $A$, of form $ underline(q)(t) = underline(v)^((i)) (alpha^((i)) cos(sqrt(lambda^((i))) t) + beta^((i)) sin(sqrt(lambda^((i))) t)) $
- *Zero mode*: solution to $dot.double(underline(q)) + A underline(q) = 0$, associated with eigenvalue $lambda^((i)) = 0$ of $A$, of form $ underline(q)(t) = underline(v)^((i)) (alpha^((i)) t + beta^((i))) $
- *Instability*: solution to $dot.double(underline(q)) + A underline(q) = 0$, associated with eigenvalue $lambda^((i)) < 0$ of $A$, of form $ underline(q)(t) = underline(v)^((i)) (alpha^((i)) cosh(sqrt(-lambda^((i))) t) + beta^((i)) sinh(sqrt(-lambda^((i))) t)) $
- When no instabilities, general solution is superposition (sum) of normal modes and zero modes.

= Fields and the wave equation

- *Generalised Euler-Lagrange equations for fields*: $ (diff cal(L)) / (diff u) - diff / (diff x) ((diff cal(L)) / (diff u_x)) - diff / (diff t) ((diff cal(L)) / (diff u_t)) = 0 $ and for $n$ fields $u^((i))$: $ (diff cal(L)) / (diff u^((i))) - diff / (diff x) ((diff cal(L)) / (diff u_x^((i)))) - diff / (diff t) ((diff cal(L)) / (diff u_t^((i)))) = 0 quad forall i $
- If fields don't depend on $(t, x)$ but on $d$ coordinates $x_i$, $ (diff cal(L)) / (diff u^((i))) - sum_(k = 1)^d diff / (diff x_k) ((diff cal(L)) / (diff u_k^((i)))) $ where $u_k^((i)) = (diff u^((i))) / (diff x_k)$
- *Massless scalar field Lagrangian*: $ cal(L) = 1/2 rho u_t^2 - 1/2 tau u_x^2 $ $rho$ is *density*, $tau$ is *tension*. The field $u$ is the *massless scalar*.
- Equation of motion for massless scalar field is $ rho u_(t t) - tau u_(x x) = 0 $ which rearranges to *wave equation*: $ u_(t t) = c^2 u_(x x) $ where $c^2 = tau \/ rho$.
- *D'Alembert's solution to wave equation*: $ u(x, t) = f(x - c t) + g(x + c t) $ $f(x - c t)$ corresponds to a wave moving to the right with speed $c$, $g(x + c t)$ corresponds to a wave moving to the left with speed $c$.
- If $u(x, 0) = phi(x)$ and $u_t(x, 0) = psi(x)$ then $ u(x, t) = 1/2 (phi(x - c t) + phi(x + c t)) + 1/(2c) integral_(x - c t)^(x + c t) psi(s) dif s $
- In field theory, *symmetry* is transformation $ u -> u' = u + epsilon a(u) $ such that $delta cal(L) = O(epsilon^2)$. $a(u)$ *generates* the transformation.
- *Note*: often, $x_0$ chosen to be $t$.
- Let $u_i = (diff u) / (diff x_i)$, *generalised momentum vector* is $ underline(Pi) := ((diff cal(L)) / (diff u_0), ..., (diff cal(L)) / (diff u_d)) $
- *Noether current* associated to transformation generated by $a$ is $ underline(J) = a underline(Pi) $
- If $underline(J)$ associated to symmetry, $ underline(nabla) dot.op underline(J) = sum_(i = 0)^d (diff J_i) / (diff x_i) = 0 $
- *(Noether) charge density*: $ cal(Q) := J_0 $
- For $d = 1$, *charge contained in interval $(a, b)$*: $ Q_((a, b)) = integral_a^b cal(Q) dif x $
- For $d = 1$, $ (d Q_((a, b))) / (d t) = J_1(a) - J_1(b) $
- *Noether charge* is total charge over all space. For $d = 1$: $ Q := Q_((-oo, oo)) = integral_(-oo)^oo J_0 dif x $
- If $d = 1$ and $lim_(x -> plus.minus oo) J_1 = 0$, $ (d Q) / (d t) = 0 $
- *Energy-momentum tensor*: $ T_(i j) := (diff cal(L)) / (diff u_j) (diff u) / (diff x_i) - delta_(i j) cal(L) $
- *Energy density*: $ cal(E) := T_(0 0) $
- *Conservation law for energy-momentum tensor*: $ sum_(j = 0)^d (diff T_(i j)) / (diff x_j) = 0 $
- *Energy flux*: $T_(t x)$.
- *Dirichlet boundary condition* for wave equation: $u_t(0, t) = 0$ (so $u(0, t) = 0$ as $u$ has shift symmetry) which gives $ u(x, t) = f(x - c t) - f(-x - c t) $ Here, waves reflected off boundary and turned upside down.
- *Neumann (free) boundary condition*: $u_x(0, t) = 0$ which gives $ u(x, t) = f(x - c t) + f(-x - c t) $ So waves reflected off boundary and not turned upside down.
- *Junction conditions*:
	- $u$ continuous at $0$: $ lim_(epsilon -> 0^+) u(epsilon, t) = lim_(epsilon -> 0^-) u(epsilon, t) $
	- Energy conservation across junction: $ d/(d t) (lim_(epsilon -> 0^+) E(-epsilon, epsilon)) = lim_(epsilon -> 0^+) (T_(t x))_(x = -epsilon) - lim_(epsilon -> 0^+) (T_(t x))_(x = epsilon) $
- *Ansatz for wave function with spring at junction at $x = 0$*: $ u(x, t) = cases(
	"Re"((e^(i p x) + R e^(-i p x)) e^(-i p c t)) & "if" x <= 0,
	"Re"(T e^(i p(x - c t))) & "if" x > 0
) $

= The Hamiltonian formalism

- *State* of classical system at given instant in time is complete set of data that fully fixes future evolution of system.
- *Phase (state) space* of system is space of all possible states system can be in at instant in time.
- *Hamiltonian formalism* parameterises phase space as generalised coordinates $underline(q)(t)$ and associated generalised momenta $underline(p)(t)$.
- When going from Lagrangian to Hamiltonian formalism, define *generalised momentum* as $ p_i := (diff L(underline(q), underline(dot(q)), t)) / (diff dot(q)_i) $
- *Poisson bracket* of $f(underline(q), underline(p), t)$ and $g(underline(q), underline(p), t)$: $ {f, g} := sum_(i = 1)^n ((diff f) / (diff q_i) (diff g) / (diff p_i) - (diff f) / (diff p_i) (diff g) / (diff q_i)) $ where $n$ is dimension of configuration space (half dimension of phase space). Position and momentum treated as independent when taking partial derivatives.
- *Properties of Poisson bracket*:
	- *Antisymmetric*: ${f, g} = -{g, f}$.
	- *Linear*: ${a f + b g, h} = a {f, h} + b {g, h}$.
	- *Leibniz identity*: ${f g, h} = f {g, h} + g {f, h}$.
	- *Jacobi identity*: ${{f, g}, h} + {{h, f}, g} + {{g, h}, f} = 0$.
- Let $cal(P)$ be phase space, $cal(F)$ be set of functions from $cal(P)$ to $RR$.
- *Hamiltonian flow* defined by $f: cal(P) -> RR$ is infinitesimal transformation on $cal(F)$ given by $ Phi_f^((e)): cal(F) -> cal(F), quad Phi_f^((e))(g) := g + epsilon{g, f} + O(epsilon^2) $
- $Phi_f^((e))$ is *generator* of map from $cal(P)$ to $cal(P)$: $ Phi_f^((e))(q_i) = q_i + epsilon (diff f) / (diff p_i) + O(epsilon^2) \ Phi_f^((e))(p_i) = p_i - epsilon (diff f) / (diff q_i) + O(epsilon^2) $
- Noether charge $Q = (sum_(i = 1)^n a_i p_i) - F$ generates symmetry transformation via Hamiltonian flow: $ Phi_Q^((e))(q_i) = q_i + epsilon {q_i, Q} + O(epsilon^2) = q_i + epsilon a_i + O(epsilon^2) $
- *Hamiltonian* gives *energy*: $ H = (sum_(i = 1)^n p_i dot(q)_i) - L $
- *Hamilton's equations of motion*: $ dot(q)_i = {q_i, H} = (diff H) / (diff p_i), quad dot(p)_i = {p_i, H} = -(diff H) / (diff q_i) $
- Time evolution of $f(underline(q), underline(p))$ generated by $H$: $ (d f) / (d t) = {f, H} $ If $f$ depends explicitly on time, $ (d f) / (d t) = (diff f) / (diff t) + {f, H} $
- *Relation between Hamiltonian and Lagrangian*: $ (diff H(underline(q), underline(p), t)) / (diff t) divides_(underline(q), underline(p)) = -(diff L(underline(q), underline(dot(q)), t)) / (diff t) divides_(underline(q), underline(dot(q))) $
- If function $Q$ doesn't depend explicitly on time, ${H, Q} = 0$ so Hamiltonian left invariant by transformation generated by $Q$: $ Phi_Q(H) = H + epsilon{Q, H} + O(epsilon^2) = H + O(epsilon^2) $

= Wave function and probabilities

- *Wave function*: continuous, complex function of position $x$ and time $t$: $psi(x, t)$.
- *Probability density to find particle at time $t$ and position $x$*: $P(x, t) = |psi(x, t)|^2$, with $ integral_(-oo)^oo P(x, t) dif x = 1 $ If this integral exists, $psi$ is *square-normalisable*. If integral equal to $1$, $psi$ is *normalised*. Probability of finding particle in interval $(a, b)$ is $ integral_a^b P(x, t) dif x $
- *Expectation value* of $f(x)$: $ angle.l f(x) angle.r = integral_(-oo)^oo f(x) P(x, t) dif x $
- *Uncertainty* in position: $Delta x = sqrt(angle.l x^2 angle.r - angle.l x angle.r^2)$
- *Infinite potential well* in $0 < x < L$: $ V(x) = cases(
	0 & "if" 0 < x < L,
	oo & "otherwise"
) $ Wave function vanishes in regions $x <= 0$ and $x >= L$. Eigenfunctions for this potential are $ phi_n(x) = sqrt(2 / L) sin((n pi x) / L) $
- *Wave function collapse*: if position is measured to be $x_0$, wave function becomes very localised around at $x_0$, and measurement immediately afterwards will also yield $x_0$.
- $angle.l x angle.r$ is not average of repeated measurements of same particle, but average of measurements of many particles with same wave function.

= Momentum and Planck's constant

- *Position operator*: $ hat(x) = x $
- *Momentum operator*: $ hat(p) = -i planck.reduce diff / (diff x) $ where $planck.reduce$ is *reduced Planck constant*.
- *Commutator*: $ [hat(x), hat(p)] := hat(x) hat(p) - hat(p) hat(x) = i planck.reduce $
- *Expectation value of momentum for wave function $psi$*: $ angle.l p angle.r = integral_(-oo)^oo overline(psi(x, t)) hat(p) psi(x, t) dif x = -i planck.reduce integral_(-oo)^oo overline(psi(x, t)) diff / (diff x) psi(x, t) dif x $
- *Expection value of function of momentum*: $ angle.l f(p) angle.r = integral_(-oo)^oo overline(psi(x, t)) f(hat(p)) psi(x, t) dif x $
- *Momentum uncertainty*: $ Delta p = sqrt(angle.l p^2 angle.r - angle.l p angle.r^2) $
- *Heisenberg's uncertainty principle*: for any normalised wave function, $ Delta x Delta p >= planck.reduce / 2 $

= Schrodinger's equation

- *Hamiltonian operator*: $ hat(H) = hat(p)^2 / (2m) + V(x) = -(planck.reduce^2) / (2m) (diff^2) / (diff x^2) + V(x) $ Corresponds to measurements of energy.
- *Schrodinger's equation*: $ i planck.reduce (diff psi(x, t)) / (diff t) = hat(H) psi(x, t) $

= The Hilbert space

- *Hermitian inner product on vector space $V$*: map $angle.l dot.op, dot.op angle.r: V times V -> CC$ satisfying:
	- $angle.l v, w angle.r = overline(angle.l w\, v angle.r)$.
	- $angle.l v, a_1 w_1 + a_2 w_2 angle.r = a_1 angle.l v, w_1 angle.r + a_2 angle.l v, w_2 angle.r$.
	- $angle.l a_1 v_1 + a_2 v_2, w angle.r = overline(a_1) angle.l v_1, w angle.r + overline(a_2) angle.l v_2, w angle.r$
	- $angle.l v, v angle.r >= 0$ for all $v$ and $angle.l v, v angle.r = 0 <==> v = 0$.
- Set of continuous square-integrable wave functions forms complex vector space. So $a_1 psi_1 + a_2 psi_2$ is also square-integrable.
- *Hermitian inner product of two wave functions*: $ angle.l psi_1, psi_2 angle.r = integral_(-oo)^oo overline(psi_1(x)) psi_2(x) dif x $ 
- If ${phi_n(x)}$ is orthonormal basis so $angle.l phi_m, phi_n angle.r = delta_(m n)$, then any vector can be expressed $ psi(x) = sum_n c_n phi_n(x) $ where $c_m = angle.l phi_m, psi angle.r$. Hermitian product is then $ angle.l psi_1, psi_2 angle.r = sum_i overline(psi_1(x)) psi_2(x) = sum_n overline(c)_(1, n) c_(2, n) $ So squared norm of $psi$ is $|psi|^2 = angle.l psi, psi angle.r = sum_n |c_n|^2$.

= Hermitian operators

- For vector space $V$, *linear operator* is map $A: V -> V$ with $ A (a_1 v_1 + a_2 v_2) = a_1 (A v_1) + a_2 (A v_2) $
- Any linear combination or composition of linear operators is linear operator.
- *Matrix elements of linear operator* for orthonormal basis ${e_j}$: $A_(i j) = angle.l e_i, A e_j angle.r$.
- *Adjoint* $A^dagger$: $angle.l v_1, A v_2 angle.r = angle.l A^dagger v_1, v_2 angle.r$. Adjoint has matrix elements which are conjugate of transpose of original matrix.
- Properties of adjoint:
	- $(a_1 A_1 + a_2 A_2)^dagger = overline(a_1) A_1^dagger + overline(a_2) A_2^dagger$.
	- $(A_1 A_2)^dagger = A_2^dagger A_1^dagger$.
- *Hermitian operator*: linear operator that is equal to adjoint. Matrix is Hermitian: $A_(i j) = overline(A_(j i))$.
- Position and momentum operators Hermitian, w.r.t. orthonomal basis of wave functions ${phi_n(x)}$.

= The spectrum of a Hermitian operator

- Wave function $psi_a$ is *eigenfunction* of Hermitian differential operator $A$ with *eigenvalue* $a$ if $A psi_a(x) = a psi_a(x)$.
- Expectation value of Hermitian operator: $ angle.l A angle.r = angle.l psi, A psi angle.r = integral_(-oo)^oo overline(psi(x)) A psi(x) dif x $.
- If $psi_a$ is eigenfunction, $angle.l A angle.r = a$ and $angle.l A^n angle.r = a^n$. So uncertainty $Delta A = 0$.
- Let $A$ Hermitian operator.
	- Eigenvalues are real and
	- $psi_1, psi_2$ eigenfunctions of $A$ with distinct eigenvalues are orthogonal.
- If $A$ has discrete spectrum, can choose orthonormal basis of eigenfunctions ${phi_n(x)}$ with eigenvalues $a_n$. Then any wave function can be written as $psi(x) = sum_n c_n phi_n(x)$ where $c_n = angle.l phi_n, psi angle.r$. Can interpret $|c_n|^2$ as probability of measurement of $A$ yielding $a_n$.
- *Dirac delta function*: $ delta(a) = cases(
	0 & "if" a != 0,
	infinity & "if" a = 0
) $ with $integral_(-oo)^oo delta(a) dif a = 1$ and $ integral_(-oo)^oo delta(a - a') f(a') dif a' = f(a) $
- *Limit definition of Dirac delta function*: limit as $epsilon -> 0^+$ of $ delta_epsilon(a) = 1/(epsilon sqrt(pi)) e^(-a^2 \/ epsilon^2) $
- *Delta funtion is Fourier transform of $1$*: $ delta(a) = 1/(2 pi) integral_(-oo)^oo e^(i a a') dif a' $
- If $A$ has continuous spectrum (eigenvalues $a in RR$) then can choose basis of eigenfunctions $phi_a(x)$ with $angle.l phi_a, phi_(a') angle.r = delta(a - a')$. Can uniquely expand wave function $ psi(x) = integral_(-oo)^oo c(a) phi_a(x) dif a $ where $c(a) = angle.l phi_a, psi angle.r $. Norm of wave function is $ angle.l psi, psi angle.r = integral_(-oo)^oo |c(a)|^2 dif a $ For normalised wave function, $ integral_(-oo)^oo |c(a)|^2 = 1 $ so treat $|c(a)|^2$ as probability distribution for measurements of $A$.

= Postulates of quantum mechanics

- *Postulates of quantum mechanics*:
	- Particle described by normalised wave function $psi(x)$.
	- Measurable quantities represented by Hermitian operators $A(x, p)$, constructed from polynomial/real analytic functions of position and momentum operators: $ hat(x) & = x,\ hat(p) & = -i planck.reduce diff / (diff x) $
	- Possible outcomes of measurement of $A$ are given by its eigenvalues $a$. If spectrum discrete, ${a_j}$, then choose eigenfunction basis $phi_j(x)$ with $angle.l phi_i, phi_j angle.r = delta_(i j)$. Then probability of finding measurement as eigenvalue $a_j$ is $|angle.l phi_j, psi angle.r|^2$. If spectrum continuous, $a in RR$, choose eigenfunctions $phi_a(x)$ with $angle.l phi_a, phi_(a') angle.r = delta(a - a')$, then probability of finding measurement as eigenvalue $a$ is $|angle.l phi_a, psi angle.r|^2$.
	- If measurement of $A$ yields eigenvalue $a_j$ (or $a$), wave function immediately afterwards is $phi_j(x)$ (or $phi_a(x)$). *Note*: in continuous case, wave function immediately afterwards not square-normalisable.
	- If no measurements made, $psi$ evolves in time according to Schrodinger equation: $ i planck.reduce (diff psi(x, t)) / (diff t) = hat(H) psi(x, t) $
- For discrete spectrum, expectation value of $A$ is $ angle.l A angle.r = sum_j a_j P_j $ for eigenvalues $a_j$, $P_j = |c_j|^2$ is probability of measurement being $a_j$.
- For continuous spectrum, expectation value of $A$ is $ angle.l A angle.r = integral_(-oo)^oo a P(a) dif a $ where $P(a) = |c(a)|^2$ is probability distribution.

= Commutators and uncertainty principle

- *Commutator* of operators $A, B$: $ [A, B] = A B - B A $
- Properties of commutator:
	- *Anti-symmetry*: $[A, B] = -[B, A]$.
	- *Linearity*: $[a_1 A_1 + a_2 A_2, B] = a_1 [A_1, B] + a_2 [A_2, B]$.
	- $[A, B C] = B[A, C] + [A, B]C$.
	- *Jacobi identity*: $[A, [B, C]] + [B, [C, A]] + [C, [A, B]] = 0$.
- If $[A, B] = 0$, possible to find orthonormal basis of wave functions which are eigenfunctions of $A$ and $B$.
- $A, B$ *compatible* if $[A, B] = 0$.
- *Generalised uncertainty principle*: for any square-normalisable wave function, $ Delta A Delta B >= 1/2 |angle.l [A, B] angle.r| $
- *Anti-commutator*: ${A, B} = A B + B A$.

= Energy revisited

- Eigenfunctions of Hamiltonian are *bound states* if classical solution is bounded in space.
- Let $V(x) >= V_0$ for all $x in RR$. Then if wave function normalised, $angle.l H angle.r > V_0$.
- If $psi(x)$ is normalised eigenfunction of $H$ with eigenvalue $E$, then $E > V_0$.
- *Zero-point energy*: smallest eigenvalue $E > V_0$.
- Spectrum of Hamiltonian is non-degenerate.

= Stationary states

- Solution to Schrodinger's equation is $psi(x, t) = phi(x) e^(-i E t \/ planck.reduce)$ where $phi(x)$ is eigenfunction of Hamiltonian with eigenvalue $E$. This solution is *stationary wave function*.
- *Full solution to Schrodinger's equation*: $ psi(x, t) = sum_j c_j phi_j(x) e^(-i E_j t \/ planck.reduce) $ where $\{phi_j(x)\}$ is orthonormal basis of Hamiltonian eigenfunctions with eigenvalues $E_j$, $c_j$ are coefficients of initial wave function expansion: $ psi(x, 0) = sum_j c_j phi_j(x) $ Probability of energy measurement being $E_j$ is $P_j = |angle.l phi_j, psi angle.r|^2 = |c_j|^2$.
- *Time-independent Schrodinger equation*: $ hat(H) phi(x) = E phi(x) $ where $phi(x)$ is Hamiltonian eigenfunction with eigenvalue (energy) $E$.

= Case study: the free particle

- If $V(x) = 0$, eigenfunction of $hat(p)$ is eigenfunction of $hat(H)$.

= Two particle systems

- For two particles in one dimension, wave function is $psi(x_1, x_2)$, probability density is $P(x_1, x_2) = |psi(x_1, x_2)|^2$: probability of finding particle one in $(a, b)$ and particle two in $(c, d)$ is $ integral_a^b integral_c^d P(x_1, x_2) dif x_1 dif x_2 $.
- Probability of finding particle one in $(a, b)$ is $ P(x_1) = integral_a^b P(x_1, x_2) dif x_2 $ (similarly for particle two).
- If both positions measured as $tilde(x)_1, tilde(x)_2$, wave function collapses to product of position eigenfunctions: $ psi_"before"(x_1, x_2) -> psi_"after"(x_1, x_2) prop delta(x_1 - tilde(x)_1) delta(x_2 - tilde(x)_2) $
- If only particle one measured, $ psi_"before"(x_1, x_2) -> delta(x_1 - tilde(x)_1) psi_"before"(tilde(x)_1, x_2) $
- Hamiltonian for two particles with zero potential: $ hat(H) = -planck.reduce^2 / (2m) diff / (diff x_1^2) - planck.reduce^2 / (2m) diff / (diff x_2^2) $ Eigenfunctions are product are single-particle eigenfunctions: $ phi(x_1, x_2) = 2/L sin((n pi x_1) / L) sin((m pi x_2) / L) $ Eigenvalues are sum of eigenvalues of single-particle Hamiltonians.
- Wave function separable if can be written as product of function of $x_1$ and function of $x_2$.
- *Entangled states*: when measurement of one particle affects subsequent measurement of other particle. Occurs for non-separable wave functions.

= Simple harmonic oscillator

- *Simple harmonic oscillator potential*: $ V(x) = 1/2 m omega^2 x^2 $ where $omega$ is angular frequency.
- If $V$ has minimum at $x = x_0$ and $|x - x_0|$ small, $m omega^2 approx 1/2 V''(x_0)$ by Taylor expanion of $V(x)$ around $x_0$.
- Energy spectrum of Hamiltonian for simple harmonic oscillator is $E_n = planck.reduce omega (n + 1/2)$

= The continuity equation

- *Probability current density*: $ J := planck.reduce / (2m i) (overline(psi) diff_x psi - psi diff_x overline(psi)) $
- *Continuity equation*: $ diff_t P + diff_x J = 0 $ where $P(x, t) = |psi(x, t)|^2$.
- Probability current vanishes as $x -> plus.minus infinity$ for square-normalisable wave functions.

= Scattering problems

- When particle has to cross potential, for $t -> -oo$, $psi(x, t) -> psi_I(x, t)$ is incoming wavepacket, then it scatters from the potential, as $t -> oo$, tends to sum of reflected and transmitted wavepackets: $ psi(x, t) -> psi_R(x, t) + psi_T(x, t) $ As $t -> oo$, reflected and transmitted wavepackets don't interfere.
- Probability of reflection is $ R = lim_(t -> oo) integral_(-oo)^oo |psi_R(x, t)|^2 dif x $ Probability of transmission is $ T = lim_(t -> oo) integral_(-oo)^oo |psi_T(x, t)|^2 dif x $ $R + T = 1$ if $psi$ normalised.

= Tunnelling

- *Finite step potential*: for $V_0 > 0$ $ V(x) = cases(
	0 & "if" x < 0,
	V_0 & "if" x >= 0
) $
- Scattering occurs when particle has energy $E > V_0$.
- Tunnelling occurs when particle has energy $0 < E < V_0$.
- For scattering, Hamiltonian eigenfunctions are $ phi(x) = cases(
	e^(i k x) + r e^(-i k x) & "if" x < 0,
	t e^(i k' x) & "if" x >= 0
) $ where $k = sqrt(2m E \/ planck.reduce^2)$, $k' = sqrt(2m(E - V_0) \/ planck.reduce^2)$
- Determine $r$ and $t$ by using that $psi$ and $diff_x psi$ continuous at $x = 0$.
- *Finite barrier potential*: $ V(x) = cases(
	0 & "if" x < 0,
	V_0 & "if" 0 <= x <= L,
	0 & "if" x > L
) $
- For tunnelling, Hamiltonian eigenfunctions are $ phi(x) = cases(
	e^(i k x) + r e^(-i k x) & "if" x < 0,
	t e^(-kappa x) & "if" x >= 0
) $ where $kappa = sqrt(2m (V_0 - E) \/ planck.reduce^2)$. Coefficients $r$ and $t$ found by replacing $k' -> i kappa$.

= Momentum-space wave function

- *Momentum-space wave function*: $ tilde(psi)(p) = 1/sqrt(2pi planck.reduce) integral_(-oo)^oo psi(x) e^(-i p x \/ planck.reduce) dif x $ satisfies $ psi(x) = 1/sqrt(2 pi planck.reduce) integral_(-oo)^oo tilde(psi)(p) e^(i p x \/ planck.reduce) dif p $
- For momentum-space wave function, position and momentum act as operators $ hat(x) & = i planck.reduce diff / (diff p) \ hat(p) = p $
- *Momentum probability density*: $tilde(P)(p) = |tilde(psi)(p)|^2$. Probability of momentum measurement being $a < p < b$ is $ integral_a^b tilde(P)(p) dif p $
- Momentum expectation value of $f(p)$: $ angle.l f(p) angle.r = integral_(-oo)^oo f(p) tilde(P)(p) dif p $
- Position expectation value of $f(x)$: $ angle.l f(x) angle.r = integral_(-oo)^oo overline(tilde(psi)(p)) f(i planck.reduce diff / (diff p)) tilde(psi)(p) dif p $
- $psi(x)$ normalised iff $tilde(psi)(p)$ normalised.
- Translating $psi(x)$ by $x_0$ multiplies $tilde(psi)(p)$ by $e^(-i p x_0 \/ planck.reduce)$.
- Translating $tilde(psi)(p)$ by $p_0$ multiplies $psi(x)$ by $e^(i p_0 x \/ planck.reduce)$.